"""Add owner table

Revision ID: 694df2655378
Revises: 1c3faeacf3fc
Create Date: 2020-04-26 08:11:14.505375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694df2655378'
down_revision = '1c3faeacf3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
